# Generated by Minecraft Display Entities Generator
summon minecraft:block_display 20.410000 62.340000 -382.000000 {block_state:{Name:"minecraft:red_concrete"},brightness:{block:15,sky:0},transformation:{left_rotation:{angle:0f,axis:[1f,0f,0f]},right_rotation:{angle:0f,axis:[1f,0f,0f]},scale:[0.680000f,1.190000f,0.170000f],translation:[0f,0f,0f]}}
summon minecraft:block_display 20.240000 62.510000 -382.000000 {block_state:{Name:"minecraft:red_concrete"},brightness:{block:15,sky:0},transformation:{left_rotation:{angle:0f,axis:[1f,0f,0f]},right_rotation:{angle:0f,axis:[1f,0f,0f]},scale:[0.170000f,1.020000f,0.170000f],translation:[0f,0f,0f]}}
# 仅用作示例
